[project]
name = "email-simplified"
version = "0.1.0"
description = "Email builder and sending handler interface."
readme = "README.md"
authors = [{ name = "David Lord" }]
license = "MIT"
license-files = ["LICENSE.txt"]
requires-python = ">=3.11"

[project.urls]
Documentation = "https://email-simplified.readthedocs.io"
Changes = "https://email-simplified.readthedocs.io/en/latest/changes/"
Source = "https://github.com/davidism/email-simplified/"

[project.entry-points."email_simplified.handler"]
smtp = "email_simplified.handlers.smtp:SMTPEmailHandler"
test = "email_simplified.handlers.test:TestEmailHandler"

[build-system]
requires = ["pdm-backend>=2.4"]
build-backend = "pdm.backend"

[dependency-groups]
dev = [
    "mypy",
    "pre-commit",
    "pyright",
    "pytest",
    "pytest-cov",
    "ruff",
    "tox",
    "tox-uv",
]
docs = [
    "furo",
    "myst-parser",
    "sphinx",
]
docs-auto = [
    "sphinx-autobuild",
]
gha-update = [
    "gha-update ; python_version>='3.12'",
]
pre-commit = [
    "pre-commit",
]
tests = [
    "pytest",
    "pytest-cov",
]
typing = [
    "mypy",
    "pyright",
    "pytest",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    "error",
]

[tool.coverage.run]
branch = true
source = ["email_simplified", "tests"]

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.report]
exclude_also = [
    "if t.TYPE_CHECKING",
    "raise NotImplementedError",
    ": \\.{3}",
]

[tool.mypy]
python_version = "3.11"
files = ["src", "tests"]
show_error_codes = true
pretty = true
strict = true

[tool.pyright]
pythonVersion = "3.11"
include = ["src", "tests"]
typeCheckingMode = "strict"

[tool.ruff]
src = ["src"]
fix = true
show-fixes = true
output-format = "full"

[tool.ruff.lint]
select = [
    "B",  # flake8-bugbear
    "E",  # pycodestyle error
    "F",  # pyflakes
    "I",  # isort
    "UP",  # pyupgrade
    "W",  # pycodestyle warning
]

[tool.ruff.lint.isort]
force-single-line = true
order-by-type = false

[tool.gha-update]
tag-only = [
    "slsa-framework/slsa-github-generator",
]

[tool.tox]
env_list = [
    "py3.13", "py3.12", "py3.11",
    "style",
    "typing",
    "docs",
]

[tool.tox.env_run_base]
runner = "uv-venv-lock-runner"
package = "wheel"
wheel_build_env = ".pkg"
constrain_package_deps = true
use_frozen_constraints = true
dependency_groups = ["tests"]
commands = [[
    "pytest", "-v", "--tb=short", "--basetemp={env_tmp_dir}",
    "--cov", "--cov-report=term-missing",
    { replace = "posargs", default = [], extend = true },
]]

[tool.tox.env.style]
dependency_groups = ["pre-commmit"]
skip_install = true
commands = [["pre-commit", "run", "--all-files"]]

[tool.tox.env.typing]
dependency_groups = ["typing"]
commands = [
    ["mypy"],
    ["pyright"],
    ["pyright", "--verifytypes", "email_simplified", "--ignoreexternal"],
]

[tool.tox.env.docs]
dependency_groups = ["docs"]
commands = [["sphinx-build", "-E", "-W", "-b", "dirhtml", "docs", "docs/_build/dirhtml"]]

[tool.tox.env.docs-auto]
dependency_groups = ["docs", "docs-auto"]
commands = [["sphinx-autobuild", "-W", "-b", "dirhtml", "--watch", "src", "docs", "docs/_build/dirhtml"]]

[tool.tox.env.update-actions]
labels = ["update"]
dependency_groups = ["gha-update"]
skip_install = true
commands = [["gha-update"]]

[tool.tox.env.update-pre_commit]
labels = ["update"]
dependency_groups = ["pre-commit"]
skip_install = true
commands = [["pre-commit", "autoupdate", "--freeze", "-j4"]]

[tool.tox.env.update-requirements]
labels = ["update"]
skip_install = true
commands = [["uv", "lock", { replace = "posargs", default = ["-U"], extend = true }]]
